---
- name: Crear nueva instancia
  os_server:
       state: present
       name: master1
       key_name: "{{ key_name }}"
       image: "{{ image }}"
       flavor: "{{ flavor }}"
       network: "{{ network }}"
       meta:
        hostname: master
  register: infra
- debug:
    var: infra

- name: Agrega instancia a inventario
  add_host:
    name: master1 
    groups: k8s
    ansible_ssh_host: "{{ infra.server.public_v4 }}"
    ansible_user: cloud-user
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"


- name: Crear nueva instancia
  os_server:
       state: present
       name: nodo11
       key_name: "{{ key_name }}"
       image: "{{ image }}"
       flavor: "{{ flavor }}"
       network: "{{ network }}"
       meta:
        hostname: nodo11
  register: infra
- debug:
    var: infra

- name: Agrega instancia a inventario
  add_host:
    name: nodo11 
    groups: k8s
    ansible_ssh_host: "{{ infra.server.public_v4 }}"
    ansible_user: cloud-user
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

- name: Crear nueva instancia
  os_server:
       state: present
       name: nodo22
       key_name: "{{ key_name }}"
       image: "{{ image }}"
       flavor: "{{ flavor }}"
       network: "{{ network }}"
       meta:
        hostname: nodo22
  register: infra
- debug:
    var: infra

- name: Agrega instancia a inventario
  add_host:
    name: nodo22 
    groups: k8s
    ansible_ssh_host: "{{ infra.server.public_v4 }}"
    ansible_user: cloud-user
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"





