---
- name: Crear nueva instancia
  os_server:
       state: present
       name: master
       key_name: "{{ key_name }}"
       image: "{{ image }}"
       flavor: "{{ flavor }}"
       network: "{{ network }}"
       meta:
        hostname: master
  register: infra
- debug:
    var: infra

- name: Agrega instancia a inventario
  add_host:
    name: master 
    groups: k8s
    ansible_ssh_host: "{{ infra.server.public_v4 }}"
    ansible_user: cloud-user
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

- name: "Get floating/public OpenStack instance IP"
  set_fact:
    instance_public_ip: "{{ item.public_v4 }}"
  when: item.name == instance_name
  loop: "{{ infra.openstack_servers }}"
  loop_control:
    label: "{{ item.name }}"

- name: Crear nueva instancia
  os_server:
       state: present
       name: nodo1
       key_name: "{{ key_name }}"
       image: "{{ image }}"
       flavor: "{{ flavor }}"
       network: "{{ network }}"
       meta:
        hostname: nodo1
  register: infra
- debug:
    var: infra

- name: Agrega instancia a inventario
  add_host:
    name: nodo1 
    groups: k8s
    ansible_ssh_host: "{{ infra.server.public_v4 }}"
    ansible_user: cloud-user
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

- name: Crear nueva instancia
  os_server:
       state: present
       name: nodo2
       key_name: "{{ key_name }}"
       image: "{{ image }}"
       flavor: "{{ flavor }}"
       network: "{{ network }}"
       meta:
        hostname: nodo2
  register: infra
- debug:
    var: infra

- name: Agrega instancia a inventario
  add_host:
    name: nodo2 
    groups: k8s
    ansible_ssh_host: "{{ infra.server.public_v4 }}"
    ansible_user: cloud-user
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"





