all:
  hosts:
    node1:
      ansible_host: 172.16.51.179
      ansible_user: cloud-user 
      ip: 192.168.25.132
      access_ip: 172.16.51.179
    node2:
      ansible_host: 172.16.51.172
      ansible_user: cloud-user
      ip: 192.168.25.177
      access_ip: 172.16.51.172
    master:
      ansible_host: 172.16.51.171
      ansible_user: cloud-user
      ip: 192.168.25.122
      access_ip: 172.16.51.171
  children:
    kube-master:
      hosts:
        master:
    kube-node:
      hosts:
        node1:
        node2:
        master:
    etcd:
      hosts:
        node1:
        node2:
        master:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
