---

- name: Install php packages
  yum: name={{ item }} state=present
  with_items:
    - php
    - php-gd
    - php-mysql
    - php-mbstring
    - php-process
    - php-xmlrpc
    - php-xml
    - libxslt
    - php-mcrypt

- easy_install:
    name: pip
    state: latest

- name: remove the rhn packages
  yum:
    name: pyOpenSSL
    state: absent

- name: install latest pyOpenSSL if needed
  pip:
    name: pyOpenSSL
    state: latest


- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - gcc-c++
    - MySQL-python

