---
- name: install python 3
  yum:
    name: python3
    state: latest 

- name: install pip
  yum:
    name: python-pip
    state: latest 
  

- name: Install openshift python package
  pip:
    name: openshift